nginx:
  hosts:
    localhost:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 22
    target:
      ansible_ssh_host: 192.168.122.117
      ansible_ssh_port: 22
  vars:
    ansible_ssh_user: root
    domain: ghasedak.ir
    tools_dir: /root/tools_new
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
