nginx:
  hosts:
    localhost:
    matrix:
      ansible_ssh_host: 192.168.122.120
      ansible_ssh_port: 33022
  vars:
    ansible_ssh_user: root
    domain: ghasedak.ir
    tools_dir: /root/tools
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
