---
galaxy_info:
  author: Mohsen Abbasi
  description: Install Matrix Synapse
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
dependencies: []
